In [1]:
import pandas as pd
import requests

In [ ]:
# "NRT" stands for Near Real-Time, meaning "recent days only."

In [ ]:
##FIRMS NASA FIRE  DATA PULLING FOR 202-2024(APRIL,MAY,JUNE)

In [11]:
MAP_KEY="2cdc83f40fbd7a1a9fe88b50922d1218"    #personal key to req data from nasa firms
area = "78.5,29.0,80.0,30.6"        # always remeber with no GAPS,BCZ  IF NOT MIGHT lead to error in undertanding by nas

In [16]:
#f"..." → this is called an "f-string" — a way to build a sentence that includes our variables inside curly brace
url = f"https://firms.modaps.eosdis.nasa.gov/api/area/csv/{MAP_KEY}/VIIRS_SNPP_NRT/{area}/5"
response = requests.get(url)
print(response.status_code)
print(url)

200
https://firms.modaps.eosdis.nasa.gov/api/area/csv/2cdc83f40fbd7a1a9fe88b50922d1218/VIIRS_SNPP_NRT/78.5,29.0,80.0,30.6/5

In [18]:
print(response.text)

latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight

In [19]:
print(area)
print(MAP_KEY)

78.5,29.0,80.0,30.6
2cdc83f40fbd7a1a9fe88b50922d1218

In [20]:
import io
df = pd.read_csv(io.StringIO(response.text))   ##IO CONVERTS CSV FORM INTO STRING FORM
print(df.shape)
df.head()

(0, 14)

Empty DataFrame
Columns: [latitude, longitude, bright_ti4, scan, track, acq_date, acq_time, satellite, instrument, confidence, version, bright_ti5, frp, daynight]
Index: []

In [23]:
test_date = "2024-04-20"
url_historical = f"https://firms.modaps.eosdis.nasa.gov/api/area/csv/{MAP_KEY}/VIIRS_SNPP_SP/{area}/5/{test_date}"
response2 = requests.get(url_historical)
print(response2.status_code)

200

In [24]:
print(response2.text)

latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight,type
29.11195,79.85496,338.14,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,306.51,3.69,D,0
29.11302,79.81827,341.36,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,309.6,5.76,D,0
29.1132,79.86288,335.71,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,309.18,2.73,D,0
29.11382,79.86684,339.64,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,308.89,2.73,D,0
29.11527,79.85435,333.36,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,304.72,3.55,D,0
29.11632,79.81759,348.64,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,307.02,4.04,D,0
29.11776,79.87019,336.61,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,305.24,2.35,D,0
29.11819,79.82946,332.34,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,303.71,2.27,D,0
29.11837,79.87411,343.63,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,306.04,2.35,D,0
29.11962,79.8169,338.63,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,302.95,4.04,D,0
29.12024,79.82085,330.23,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,303.03,4.49,D,0
29.12087,79.82482,349.15,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,305.4,4.49,D,0
29.12149,79.82879,339.26,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,303.08,2.27,D,0
29.12168,79.8735,335.15,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,306.33,2.35,D,0
29.12499,79.87285,330.89,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,304.03,2.4,D,0
29.12953,79.38889,349.15,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,309.78,6.14,D,0
29.13098,79.86758,332.93,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,304.96,3.19,D,0
29.13507,79.91547,350.02,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,307.26,4.31,D,0
29.18046,79.92252,348.86,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,307.83,8.18,D,0
29.18107,79.92646,338.16,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,307.52,8.18,D,0
29.18377,79.9219,356.47,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,314.04,8.18,D,0
29.18438,79.92582,351.25,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,307.55,8.18,D,0
29.18487,79.80073,348.4,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,313.15,7.28,D,0
29.18646,79.91735,340.07,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,310.35,4.59,D,0
29.18707,79.92129,355.04,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,315.99,15.96,D,0
29.18768,79.92519,339.3,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,306.85,15.96,D,0
29.18818,79.8001,348.18,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,311.28,5.79,D,0
29.18977,79.91675,337,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,308.28,4.59,D,0
29.19099,79.92458,367,0.39,0.36,2024-04-20,743,N,VIIRS,h,2,309.98,15.96,D,0
29.19368,79.92007,339.61,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,305.66,12.85,D,0
29.19429,79.92397,355.89,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,312.79,12.85,D,0
29.19699,79.91947,355.54,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,317.22,12.85,D,0
29.1976,79.92336,335.75,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,304.21,12.85,D,0
29.1981,79.99223,334.21,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,306.96,2.7,D,0
29.1987,79.99615,332.49,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,307.47,2.7,D,0
29.20016,79.91985,346.66,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,308.61,10.22,D,0
29.20139,79.9915,334.57,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,305.55,2.7,D,0
29.20348,79.91924,347.04,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,301.87,10.22,D,0
29.20553,79.91064,331.5,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,305.7,2.9,D,0
29.20799,79.99011,352.31,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,309.52,5.99,D,0
29.2129,79.33025,338.83,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,307,2.06,D,0
29.21469,79.33012,333.38,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,305.36,1.19,D,0
29.22103,79.81387,335.26,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,307.69,2.57,D,0
29.24173,79.37003,342.37,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,311.55,3.49,D,0
29.25557,79.09294,367,0.39,0.37,2024-04-20,743,N,VIIRS,h,2,335.34,46.54,D,0
29.25622,79.09698,346.12,0.39,0.37,2024-04-20,743,N,VIIRS,n,2,315.65,46.54,D,0
29.25891,79.09225,367,0.39,0.37,2024-04-20,743,N,VIIRS,h,2,312.77,17.24,D,0
29.26232,79.83826,340.62,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,308.43,2.69,D,0
29.26468,79.91873,332.07,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,304.65,2.67,D,0
29.2848,79.5106,336.83,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,302.73,3.67,D,0
29.28876,79.51396,337.32,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,304.14,3.67,D,0
29.28938,79.51791,330.02,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,304.61,3.12,D,0
29.29208,79.51331,338.78,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,306.04,4.13,D,0
29.31808,79.85114,342.5,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,307.95,3.9,D,0
29.31834,79.44163,330.7,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,303.9,1.5,D,0
29.32957,79.53406,338,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,308.08,7.02,D,0
29.33009,79.47269,349.16,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,301.99,3.89,D,0
29.33022,79.53814,339.16,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,307.41,7.02,D,0
29.33215,79.83215,334.25,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,303.65,3.57,D,0
29.33276,79.83602,339.9,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,306.49,8.32,D,0
29.3329,79.53349,340.31,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,308.45,7.02,D,0
29.33354,79.53757,354.55,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,310.32,7.02,D,0
29.33622,79.53293,333.68,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,305,2.43,D,0
29.34633,79.40765,341.26,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,303.6,3.76,D,0
29.34822,79.86955,332.48,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,306.48,2.85,D,0
29.34884,79.87353,349.48,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,309.5,8.31,D,0
29.34966,79.40705,338.88,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,305.27,5.72,D,0
29.35214,79.8729,354.66,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,306.52,8.31,D,0
29.3778,79.56184,347.01,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,302.66,7.15,D,0
29.37988,79.55338,337.38,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,304.53,3.28,D,0
29.38112,79.5612,337.53,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,302.64,2.79,D,0
29.38332,79.85458,330.59,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,302.23,2.37,D,0
29.38617,79.50698,330.01,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,302.44,1.52,D,0
29.38905,79.71914,342.81,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,301.4,4.46,D,0
29.39297,79.72239,331.18,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,298.82,7.26,D,0
29.40829,79.97133,342.41,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,305.32,9.66,D,0
29.45769,79.89639,335.11,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,308.83,2.09,D,0
29.4583,79.9003,349.52,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,309.62,6.83,D,0
29.46161,79.89967,339.43,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,309.57,3.18,D,0
29.46474,79.85427,344.76,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,311.09,6.12,D,0
29.46535,79.85817,338.72,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,307.34,4.87,D,0
29.47063,79.91393,333.57,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,307.6,1.46,D,0
29.49449,79.05647,345.65,0.39,0.37,2024-04-20,743,N,VIIRS,n,2,310.21,11.84,D,0
29.49514,79.06047,367,0.39,0.37,2024-04-20,743,N,VIIRS,h,2,313.75,24.58,D,0
29.49644,79.05656,352.46,0.39,0.37,2024-04-20,743,N,VIIRS,n,2,308.01,6.97,D,0
29.49709,79.06057,347.8,0.39,0.37,2024-04-20,743,N,VIIRS,n,2,305.76,9.29,D,0
29.49978,79.0559,344.34,0.39,0.37,2024-04-20,743,N,VIIRS,n,2,309.34,6.97,D,0
29.50059,79.99731,335.01,0.38,0.36,2024-04-20,743,N,VIIRS,l,2,309.15,12.4,D,0
29.51055,79.03726,334.8,0.39,0.37,2024-04-20,743,N,VIIRS,n,2,306.12,2.59,D,0
29.51121,79.04132,351.22,0.39,0.37,2024-04-20,743,N,VIIRS,n,2,307.35,8.06,D,0
29.51389,79.03658,346.66,0.39,0.37,2024-04-20,743,N,VIIRS,n,2,307.97,11.15,D,0
29.51788,79.03987,331.3,0.39,0.37,2024-04-20,743,N,VIIRS,l,2,304.2,6.28,D,0
29.51884,79.15187,335.44,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,306.66,1.92,D,0
29.51918,79.04792,337.73,0.39,0.37,2024-04-20,743,N,VIIRS,n,2,304.97,2.87,D,0
29.53352,79.36509,344.64,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,306.07,7.37,D,0
29.53991,79.64294,340.57,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,306.11,4.44,D,0
29.55531,79.45921,344.85,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,304.72,3.05,D,0
29.55766,79.9088,342.11,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,307.01,5.61,D,0
29.55861,79.45841,341.54,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,304.14,3.05,D,0
29.56271,79.31732,341.53,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,309.52,4.17,D,0
29.57502,79.88914,347.73,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,305.17,5.3,D,0
29.61568,79.34859,339.96,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,300.16,3.68,D,0
29.62309,79.33069,342,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,300.64,5.08,D,0
29.62448,79.9886,336.76,0.38,0.36,2024-04-20,743,N,VIIRS,l,2,308.91,3.35,D,0
29.63853,79.27673,331.68,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,304.07,1.12,D,0
29.6406,79.27718,342.17,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,308.02,3.63,D,0
29.64392,79.27646,345.62,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,303.56,3.63,D,0
29.64812,79.21738,344.15,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,308.37,5.2,D,0
29.65084,79.21287,367,0.39,0.36,2024-04-20,743,N,VIIRS,h,2,308.77,7.05,D,0
29.65146,79.21677,343.16,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,305.71,7.05,D,0
29.65261,79.07487,346.74,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,308.04,4.54,D,0
29.65595,79.0742,334.56,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,308.05,2.38,D,0
29.67583,79.26156,335.31,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,306.96,4.29,D,0
29.67848,79.25673,343.44,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,310.19,11.04,D,0
29.67914,79.26081,336.01,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,307.52,11.04,D,0
29.69054,79.95535,340.06,0.38,0.36,2024-04-20,743,N,VIIRS,n,2,310.12,4.73,D,0
29.69702,79.13696,333.43,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,305.5,2.1,D,0
29.72355,79.25961,332.51,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,307.49,1.14,D,0
29.72752,79.26304,352.17,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,310.49,11.92,D,0
29.72799,79.84588,335.9,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,308.05,3.2,D,0
29.72817,79.26717,348.98,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,310.89,11.92,D,0
29.73084,79.26237,352.57,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,308.06,11.92,D,0
29.73743,79.99489,339.77,0.38,0.36,2024-04-20,743,N,VIIRS,n,2,307.47,5.51,D,0
29.74073,79.9942,338.03,0.38,0.36,2024-04-20,743,N,VIIRS,n,2,305.65,2.71,D,0
29.7582,79.97907,345.36,0.38,0.36,2024-04-20,743,N,VIIRS,n,2,308.82,4.9,D,0
29.77495,79.41518,333.53,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,303.03,1.71,D,0
29.77679,78.69559,346.53,0.4,0.37,2024-04-20,743,N,VIIRS,n,2,307.06,5.05,D,0
29.77728,79.21581,344.1,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,306.92,3.1,D,0
29.78576,79.48304,330.2,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,304.69,3.06,D,0
29.81906,78.57289,333.98,0.4,0.37,2024-04-20,743,N,VIIRS,n,2,307.8,2.71,D,0
29.82218,79.90911,337.6,0.38,0.36,2024-04-20,743,N,VIIRS,l,2,307.62,3.06,D,0
29.84257,79.90916,344.8,0.38,0.36,2024-04-20,743,N,VIIRS,n,2,308.17,6.15,D,0
29.85061,78.61676,330.95,0.4,0.37,2024-04-20,743,N,VIIRS,l,2,304.21,2.6,D,0
29.85725,79.93901,351.7,0.38,0.36,2024-04-20,743,N,VIIRS,n,2,312.92,5.67,D,0
29.85731,79.35228,343.97,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,305.57,6.33,D,0
29.87251,79.44844,331.61,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,302.91,4.18,D,0
29.87824,79.02037,337.1,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,300.7,24.69,D,0
29.87889,79.02436,334.63,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,302.64,12.92,D,0
29.88221,79.02364,337.74,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,302.34,12.92,D,0
29.88291,79.47122,337.89,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,308.29,6.75,D,0
29.88622,79.47062,336.76,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,305.9,6.75,D,0
29.88622,79.81884,335.42,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,307.32,2.13,D,0
29.88686,79.47465,367,0.39,0.36,2024-04-20,743,N,VIIRS,h,2,310.8,6.75,D,0
29.88931,79.47439,335.64,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,298.85,4.24,D,0
29.91647,79.99238,330.08,0.38,0.36,2024-04-20,743,N,VIIRS,l,2,303.96,2.09,D,0
29.93367,79.92757,330.22,0.38,0.36,2024-04-20,743,N,VIIRS,l,2,303.62,1.68,D,0
29.95604,79.46469,330.1,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,295.63,3.7,D,0
29.95815,79.34838,337.62,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,303.27,5.65,D,0
29.96423,79.9091,346.69,0.38,0.36,2024-04-20,743,N,VIIRS,n,2,311.06,3.87,D,0
29.96985,79.87945,337.52,0.38,0.36,2024-04-20,743,N,VIIRS,n,2,307.3,2.09,D,0
29.97046,79.88339,336.44,0.38,0.36,2024-04-20,743,N,VIIRS,n,2,306.06,2.09,D,0
29.97077,79.42818,345.45,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,304.02,4.33,D,0
29.97163,79.95678,338.08,0.38,0.36,2024-04-20,743,N,VIIRS,n,2,305.07,5.5,D,0
29.99782,79.90638,336.39,0.38,0.36,2024-04-20,743,N,VIIRS,n,2,308.31,3.46,D,0
29.99842,79.91032,332.93,0.38,0.36,2024-04-20,743,N,VIIRS,n,2,307.77,3.46,D,0
30.00046,79.66083,343.17,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,312.61,4.87,D,0
30.00112,79.90576,341.73,0.38,0.36,2024-04-20,743,N,VIIRS,n,2,308.59,3.46,D,0
29.86262,78.57695,336.04,0.4,0.37,2024-04-20,744,N,VIIRS,n,2,301.92,4.04,D,0
29.87273,78.63799,337.98,0.4,0.37,2024-04-20,744,N,VIIRS,n,2,306.79,3.54,D,0
29.87712,78.51775,332.02,0.4,0.37,2024-04-20,744,N,VIIRS,l,2,303.82,2.96,D,0
29.87783,78.52201,335.28,0.4,0.37,2024-04-20,744,N,VIIRS,n,2,305.92,2.96,D,0
29.9774,79.34466,331.01,0.39,0.36,2024-04-20,744,N,VIIRS,l,2,303.04,2.78,D,0
30.00332,79.33553,330.19,0.39,0.36,2024-04-20,744,N,VIIRS,l,2,300.81,3.2,D,0
30.06457,79.61519,331.7,0.39,0.36,2024-04-20,744,N,VIIRS,l,2,304.25,2.79,D,0
30.13245,78.57897,346.05,0.4,0.37,2024-04-20,744,N,VIIRS,n,2,309.01,6.45,D,0
30.16927,78.61307,349.66,0.4,0.37,2024-04-20,744,N,VIIRS,n,2,310.73,5.19,D,0
30.29438,79.14169,336.2,0.39,0.36,2024-04-20,744,N,VIIRS,n,2,306.56,3.19,D,0
29.10844,79.86063,332.36,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,294.02,3.05,N,0
29.10905,79.85565,311.53,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,293.2,3.34,N,0
29.10955,79.81309,317.99,0.49,0.41,2024-04-20,2008,N,VIIRS,n,2,295.32,3.02,N,0
29.11019,79.81522,314.01,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,294.97,2.37,N,0
29.11023,79.87707,302.85,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,289.11,1,N,0
29.11083,79.81,319.42,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,294.59,2.37,N,0
29.11086,79.87198,306.12,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,290.86,1,N,0
29.11149,79.86678,311.67,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,292.18,3.05,N,0
29.11394,79.87782,329.91,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,290.87,2.43,N,0
29.11451,79.81107,317.67,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,294.21,1.23,N,0
29.11454,79.87293,307.31,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,290.98,2.43,N,0
29.11574,79.83222,329.98,0.49,0.41,2024-04-20,2008,N,VIIRS,n,2,293.93,4.25,N,0
29.11633,79.82738,313.38,0.49,0.41,2024-04-20,2008,N,VIIRS,n,2,293.25,2.91,N,0
29.11703,79.85271,305.12,0.49,0.41,2024-04-20,2008,N,VIIRS,n,2,292.38,1.16,N,0
29.11764,79.87864,319.64,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,291.99,2.43,N,0
29.11823,79.81181,304.34,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,292.72,1.23,N,0
29.11944,79.83309,329.82,0.49,0.41,2024-04-20,2008,N,VIIRS,n,2,293.59,3.92,N,0
29.12135,79.81748,316.96,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,293.4,3.44,N,0
29.12135,79.87939,311.82,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,292.36,1.36,N,0
29.12383,79.82832,317.55,0.49,0.41,2024-04-20,2008,N,VIIRS,n,2,293.23,2.48,N,0
29.12449,79.82287,322.51,0.49,0.41,2024-04-20,2008,N,VIIRS,n,2,293.68,2.48,N,0
29.12564,79.87537,306.8,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,291.7,1.36,N,0
29.12932,79.90696,303.3,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,288.69,0.78,N,0
29.18047,79.95229,303.79,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,271.42,0.58,N,0
29.18521,79.98508,297.59,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,276.01,0.45,N,0
29.18776,79.98415,318.23,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,277.63,1.31,N,0
29.18838,79.97929,299.22,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,273.6,1.31,N,0
29.18889,79.98592,303.5,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,277.96,0.45,N,0
29.18896,79.97478,306.43,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,273.86,0.74,N,0
29.1895,79.98099,312.7,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,278.01,1.65,N,0
29.18955,79.97016,301.79,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,276.32,0.74,N,0
29.19008,79.9763,315.5,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,279.69,1.65,N,0
29.19065,79.97171,311.71,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,280.89,1.35,N,0
29.19207,79.98005,303.56,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,279.9,1.21,N,0
29.19268,79.97532,312.76,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,280.21,2.07,N,0
29.19378,79.97694,303.29,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,283.54,0.88,N,0
29.19543,79.92416,318.73,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,288.05,3.85,N,0
29.19626,79.92572,323.22,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,286.19,2.79,N,0
29.19682,79.92123,325.08,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,289.52,4.96,N,0
29.19909,79.92522,330.7,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,289.58,3.13,N,0
29.19965,79.9208,333.24,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,290.43,3.13,N,0
29.20048,79.92239,336.35,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,290.7,3.14,N,0
29.2033,79.92191,304.63,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,288.38,3.13,N,0
29.20391,79.91705,303.89,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,287.26,1.16,N,0
29.20473,79.91871,309,0.49,0.4,2024-04-20,2008,N,VIIRS,n,2,288.05,3.14,N,0
29.22222,79.6826,303.83,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,290.32,1.04,N,0
29.22613,79.67888,301,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,290.3,2.33,N,0
29.22668,79.6777,324.48,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,290.84,3.17,N,0
29.2267,79.67419,331.3,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,290.99,4.46,N,0
29.22726,79.67309,325.41,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,290.63,3.17,N,0
29.22995,79.67904,317.71,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,291.3,2.01,N,0
29.2305,79.67789,319.6,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,291.84,2.78,N,0
29.23051,79.67438,314.31,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,291.09,2.04,N,0
29.25882,79.6627,306.51,0.51,0.41,2024-04-20,2008,N,VIIRS,n,2,290.88,1.32,N,0
29.284,79.51855,302.56,0.51,0.41,2024-04-20,2008,N,VIIRS,n,2,290.28,0.64,N,0
29.28777,79.51945,304.66,0.51,0.41,2024-04-20,2008,N,VIIRS,n,2,289.65,0.75,N,0
29.29107,79.49206,304.41,0.52,0.41,2024-04-20,2008,N,VIIRS,n,2,290.2,0.78,N,0
29.31606,79.44597,310.42,0.52,0.41,2024-04-20,2008,N,VIIRS,n,2,292.75,1.42,N,0
29.31671,79.44065,315.07,0.52,0.41,2024-04-20,2008,N,VIIRS,n,2,293.24,2.47,N,0
29.32301,79.57915,299.51,0.51,0.41,2024-04-20,2008,N,VIIRS,n,2,288.07,0.69,N,0
29.3268,79.83082,300.58,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,285.71,1.03,N,0
29.32697,79.86057,301.51,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,282.09,0.75,N,0
29.32834,79.4728,301.23,0.52,0.41,2024-04-20,2008,N,VIIRS,n,2,289.04,0.78,N,0
29.35166,79.4096,313.47,0.52,0.42,2024-04-20,2008,N,VIIRS,n,2,284.82,0.98,N,0
29.35223,79.40488,313.1,0.52,0.42,2024-04-20,2008,N,VIIRS,n,2,288.14,1.72,N,0
29.35286,79.39974,305.63,0.52,0.42,2024-04-20,2008,N,VIIRS,n,2,288.38,1.72,N,0
29.35864,79.46862,305.43,0.52,0.41,2024-04-20,2008,N,VIIRS,n,2,287.97,1.06,N,0
29.35938,79.4291,307.93,0.52,0.42,2024-04-20,2008,N,VIIRS,n,2,289.08,1.24,N,0
29.35948,79.47233,303.28,0.52,0.41,2024-04-20,2008,N,VIIRS,n,2,288.45,1.39,N,0
29.36005,79.46767,310.44,0.52,0.41,2024-04-20,2008,N,VIIRS,n,2,288.16,1.39,N,0
29.36105,79.42825,304.63,0.52,0.42,2024-04-20,2008,N,VIIRS,n,2,288.44,0.74,N,0
29.36245,79.46926,326.71,0.52,0.41,2024-04-20,2008,N,VIIRS,n,2,289.34,3.71,N,0
29.36385,79.46837,315.19,0.52,0.41,2024-04-20,2008,N,VIIRS,n,2,288.45,2.04,N,0
29.36891,79.57752,313.22,0.51,0.41,2024-04-20,2008,N,VIIRS,n,2,287.11,1.94,N,0
29.36952,79.57247,310.46,0.51,0.41,2024-04-20,2008,N,VIIRS,n,2,286.6,1.94,N,0
29.37272,79.57806,310.02,0.51,0.41,2024-04-20,2008,N,VIIRS,n,2,287.14,3.72,N,0
29.37331,79.57312,306.43,0.51,0.41,2024-04-20,2008,N,VIIRS,n,2,287.63,3.72,N,0
29.37391,79.56818,298.54,0.51,0.41,2024-04-20,2008,N,VIIRS,n,2,285.94,1.54,N,0
29.37706,79.57408,338.53,0.51,0.41,2024-04-20,2008,N,VIIRS,n,2,291.1,3.72,N,0
29.37766,79.56914,312.8,0.51,0.41,2024-04-20,2008,N,VIIRS,n,2,287.18,1.54,N,0
29.38081,79.57505,321.18,0.51,0.41,2024-04-20,2008,N,VIIRS,n,2,287.53,2.56,N,0
29.38141,79.57012,307.78,0.51,0.41,2024-04-20,2008,N,VIIRS,n,2,286.9,2.13,N,0
29.38295,79.71571,305.97,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,286.87,1.91,N,0
29.38352,79.71107,327.24,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,289.38,4.35,N,0
29.38615,79.72085,313.26,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,287.21,1.2,N,0
29.38785,79.70715,301.36,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,286.02,1.15,N,0
29.38993,79.72134,301.42,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,285.64,1.2,N,0
29.39049,79.7168,297.01,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,285.99,1.2,N,0
29.3905,79.80947,295.32,0.5,0.41,2024-04-20,2008,N,VIIRS,n,2,282.08,0.31,N,0

In [25]:
df_historical = pd.read_csv(io.StringIO(response2.text))
print(df_historical.shape)
df_historical.head()

(1323, 15)

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight,type
0,29.11195,79.85496,338.14,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,306.51,3.69,D,0
1,29.11302,79.81827,341.36,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,309.60,5.76,D,0
2,29.11320,79.86288,335.71,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,309.18,2.73,D,0
3,29.11382,79.86684,339.64,0.39,0.36,2024-04-20,743,N,VIIRS,n,2,308.89,2.73,D,0
4,29.11527,79.85435,333.36,0.39,0.36,2024-04-20,743,N,VIIRS,l,2,304.72,3.55,D,0

In [27]:
df_historical.shape

(1323, 15)

In [28]:
df_historical.to_csv("../data/raw/firms_2024-04-20_sample.csv", index=False)   #STORING DATAFRAMES AS IN CSV FILE IN OUR FILE ADDRESS
print("Saved!")

Saved!

In [29]:
import datetime

start = datetime.date(2024, 4, 1)
end = datetime.date(2024, 6, 30)

dates_to_pull = []
current = start
while current <= end:
    dates_to_pull.append(current.strftime("%Y-%m-%d"))
    current += datetime.timedelta(days=5)

print(len(dates_to_pull))
print(dates_to_pull[:5])

19
['2024-04-01', '2024-04-06', '2024-04-11', '2024-04-16', '2024-04-21']

In [30]:
import time

all_data = []

for date in dates_to_pull:
    url = f"https://firms.modaps.eosdis.nasa.gov/api/area/csv/{MAP_KEY}/VIIRS_SNPP_SP/{area}/5/{date}"
    response = requests.get(url)
    
    if response.status_code == 200:
        temp_df = pd.read_csv(io.StringIO(response.text))
        all_data.append(temp_df)
        print(date, "->", temp_df.shape[0], "fires found")
    else:
        print(date, "-> FAILED, status code:", response.status_code)
    
    time.sleep(1)

2024-04-01 -> 241 fires found
2024-04-06 -> 1043 fires found
2024-04-11 -> 253 fires found
2024-04-16 -> 986 fires found
2024-04-21 -> 1718 fires found
2024-04-26 -> 1576 fires found
2024-05-01 -> 3641 fires found
2024-05-06 -> 605 fires found
2024-05-11 -> 150 fires found
2024-05-16 -> 315 fires found
2024-05-21 -> 67 fires found
2024-05-26 -> 86 fires found
2024-05-31 -> 6 fires found
2024-06-05 -> 163 fires found
2024-06-10 -> 846 fires found
2024-06-15 -> 567 fires found
2024-06-20 -> 9 fires found
2024-06-25 -> 1 fires found
2024-06-30 -> 0 fires found

In [31]:
df_season_2024 = pd.concat(all_data, ignore_index=True)
print(df_season_2024.shape)
df_season_2024.head()

(12273, 15)

C:\Users\dolly\AppData\Local\Temp\ipykernel_9432\3665869033.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_season_2024 = pd.concat(all_data, ignore_index=True)

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight,type
0,29.57618,79.35428,335.68,0.54,0.68,2024-04-01,840,N,VIIRS,n,2,294.81,2.68,D,0
1,29.57858,79.35174,327.62,0.54,0.68,2024-04-01,840,N,VIIRS,n,2,296.31,4.07,D,0
2,29.71142,79.29804,335.84,0.54,0.68,2024-04-01,840,N,VIIRS,n,2,291.65,4.72,D,0
3,29.06977,79.96082,295.96,0.35,0.56,2024-04-01,2104,N,VIIRS,n,2,283.83,0.74,N,0
4,29.10752,79.82458,301.99,0.34,0.56,2024-04-01,2104,N,VIIRS,n,2,288.11,0.58,N,0

In [32]:
df_season_2024.to_csv("../data/raw/firms_2024_season.csv", index=False)
print("Saved! Total fires:", df_season_2024.shape[0])

Saved! Total fires: 12273

In [33]:
years = [2020, 2021, 2022, 2023, 2024]
all_dates_multi_year = []

for year in years:
    start = datetime.date(year, 4, 1)
    end = datetime.date(year, 6, 30)
    current = start
    while current <= end:
        all_dates_multi_year.append(current.strftime("%Y-%m-%d"))
        current += datetime.timedelta(days=5)

print(len(all_dates_multi_year))
print(all_dates_multi_year[:3])
print(all_dates_multi_year[-3:])

95
['2020-04-01', '2020-04-06', '2020-04-11']
['2024-06-20', '2024-06-25', '2024-06-30']

In [35]:
def get_fires_for_date(date):  #1TIME CODE RUNS N NUMBER TIME 
    url = f"https://firms.modaps.eosdis.nasa.gov/api/area/csv/{MAP_KEY}/VIIRS_SNPP_SP/{area}/5/{date}"
    response = requests.get(url)
    
    if response.status_code == 200:
        temp_df = pd.read_csv(io.StringIO(response.text))
        return temp_df
    else:
        print(date, "-> FAILED, status code:", response.status_code)
        return None

In [36]:
all_data_multi_year = []

for date in all_dates_multi_year:
    result = get_fires_for_date(date)
    if result is not None:
        all_data_multi_year.append(result)
        print(date, "->", result.shape[0], "fires found")
    time.sleep(1)

print("DONE. Total chunks collected:", len(all_data_multi_year))

2020-04-01 -> 11 fires found
2020-04-06 -> 16 fires found
2020-04-11 -> 11 fires found
2020-04-16 -> 17 fires found
2020-04-21 -> 21 fires found
2020-04-26 -> 11 fires found
2020-05-01 -> 23 fires found
2020-05-06 -> 8 fires found
2020-05-11 -> 23 fires found
2020-05-16 -> 96 fires found
2020-05-21 -> 108 fires found
2020-05-26 -> 88 fires found
2020-05-31 -> 1 fires found
2020-06-05 -> 3 fires found
2020-06-10 -> 11 fires found
2020-06-15 -> 8 fires found
2020-06-20 -> 6 fires found
2020-06-25 -> 3 fires found
2020-06-30 -> 3 fires found
2021-04-01 -> 3279 fires found
2021-04-06 -> 1140 fires found
2021-04-11 -> 2564 fires found
2021-04-16 -> 519 fires found
2021-04-21 -> 88 fires found
2021-04-26 -> 336 fires found
2021-05-01 -> 144 fires found
2021-05-06 -> 66 fires found
2021-05-11 -> 26 fires found
2021-05-16 -> 40 fires found
2021-05-21 -> 11 fires found
2021-05-26 -> 4 fires found
2021-05-31 -> 3 fires found
2021-06-05 -> 6 fires found
2021-06-10 -> 2 fires found
2021-06-15 -> 0 fires found
2021-06-20 -> 0 fires found
2021-06-25 -> 1 fires found
2021-06-30 -> 3 fires found
2022-04-01 -> 467 fires found
2022-04-06 -> 432 fires found
2022-04-11 -> 316 fires found
2022-04-16 -> 2157 fires found
2022-04-21 -> 2137 fires found
2022-04-26 -> 1683 fires found
2022-05-01 -> 417 fires found
2022-05-06 -> 153 fires found
2022-05-11 -> 37 fires found
2022-05-16 -> 89 fires found
2022-05-21 -> 61 fires found
2022-05-26 -> 9 fires found
2022-05-31 -> 351 fires found
2022-06-05 -> 365 fires found
2022-06-10 -> 127 fires found
2022-06-15 -> 30 fires found
2022-06-20 -> 8 fires found
2022-06-25 -> 1 fires found
2022-06-30 -> 1 fires found
2023-04-01 -> 7 fires found
2023-04-06 -> 45 fires found
2023-04-11 -> 172 fires found
2023-04-16 -> 249 fires found
2023-04-21 -> 146 fires found
2023-04-26 -> 45 fires found
2023-05-01 -> 0 fires found
2023-05-06 -> 44 fires found
2023-05-11 -> 129 fires found
2023-05-16 -> 100 fires found
2023-05-21 -> 88 fires found
2023-05-26 -> 8 fires found
2023-05-31 -> 46 fires found
2023-06-05 -> 374 fires found
2023-06-10 -> 423 fires found
2023-06-15 -> 275 fires found
2023-06-20 -> 17 fires found
2023-06-25 -> 1 fires found
2023-06-30 -> 0 fires found
2024-04-01 -> 241 fires found
2024-04-06 -> 1043 fires found
2024-04-11 -> 253 fires found
2024-04-16 -> 986 fires found
2024-04-21 -> 1718 fires found
2024-04-26 -> 1576 fires found
2024-05-01 -> 3641 fires found
2024-05-06 -> 605 fires found
2024-05-11 -> 150 fires found
2024-05-16 -> 315 fires found
2024-05-21 -> 67 fires found
2024-05-26 -> 86 fires found
2024-05-31 -> 6 fires found
2024-06-05 -> 163 fires found
2024-06-10 -> 846 fires found
2024-06-15 -> 567 fires found
2024-06-20 -> 9 fires found
2024-06-25 -> 1 fires found
2024-06-30 -> 0 fires found
DONE. Total chunks collected: 95

In [37]:
df_all_years = pd.concat(all_data_multi_year, ignore_index=True)   # CONCATINATES 2 DATAFRAMES STACKING ON TOP OF EACH ITHER 
print(df_all_years.shape)
df_all_years['acq_date'] = pd.to_datetime(df_all_years['acq_date'])
print(df_all_years['acq_date'].min(), "to", df_all_years['acq_date'].max())

(31983, 15)
2020-04-02 00:00:00 to 2024-06-25 00:00:00

C:\Users\dolly\AppData\Local\Temp\ipykernel_9432\698215915.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all_years = pd.concat(all_data_multi_year, ignore_index=True)

In [38]:
df_all_years.to_csv("../data/raw/firms_2020_2024_season.csv", index=False)
print("Saved! Total rows:", df_all_years.shape[0])

Saved! Total rows: 31983

In [ ]:
##FIRMS NASA FIRE  DATA PULLED FOR 202-2024(APRIL,MAY,JUNE)

In [ ]:
##WEATHER DATA PULLING FOR 202-2024(APRIL,MAY,JUNE)